-- CREATE DATABASE chat_db;
-- USE chat_db;
-- 
-- -- Messages-only schema for the new model
-- -- Table: messages (id, lobby_id, sender_user_id, room_id, content, timestamp, is_radio, is_blocked)
-- 
-- CREATE TABLE IF NOT EXISTS messages (
--                                         id INT AUTO_INCREMENT PRIMARY KEY,
--                                         lobby_id INT NULL,
--                                         sender_user_id INT NOT NULL,
--                                         room_id INT NULL,
--                                         content TEXT NOT NULL,
--                                         timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--                                         is_radio BOOLEAN NOT NULL DEFAULT FALSE,
--                                         is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
--                                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- 
-- -- Helpful indexes to mirror common query patterns
-- CREATE INDEX ix_messages_lobby_ts ON messages (lobby_id, timestamp);
-- CREATE INDEX ix_messages_room_ts  ON messages (room_id, timestamp);
-- CREATE INDEX ix_messages_sender_ts ON messages (sender_user_id, timestamp);
-- 
-- -- -------------------------------------------------------------------
-- -- Sample seed data (no users/rooms/memberships anymore).
-- -- Adjust sender_user_id / lobby_id / room_id values to whatever your app expects.
-- -- -------------------------------------------------------------------
-- 
-- INSERT INTO messages (lobby_id, sender_user_id, room_id, content, timestamp, is_radio, is_blocked)
-- VALUES
--     (1, 1, NULL, 'Hello lobby 1! Welcome everyone.', NOW(), FALSE, FALSE),
--     (1, 2, NULL, 'Hey! Glad to be here in lobby 1.', NOW(), FALSE, FALSE),
--     (NULL, 3, 2, 'Any updates from room 2?', NOW(), FALSE, FALSE),
--     (NULL, 4, 2, 'Not yet—listening in.', NOW(), FALSE, FALSE),
--     (NULL, 1, 3, 'Testing a radio-style broadcast in room 3.', NOW(), TRUE,  FALSE),
--     (1, 3, NULL, 'Broadcast to lobby 1 via radio.', NOW(), TRUE,  FALSE),
--     (NULL, 2, 2, 'This one is blocked by moderation.', NOW(), FALSE, TRUE);
-- 
-- 
-- CREATE DATABASE inventory_db;
-- 
-- USE inventory_db;
-- 
-- -- 000_inventory_schema.sql
-- CREATE DATABASE IF NOT EXISTS inventory_db
--     CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE inventory_db;
-- 
-- -- Single-table schema used by your FastAPI service
-- CREATE TABLE IF NOT EXISTS inventory (
--                                          id INT AUTO_INCREMENT PRIMARY KEY,
--                                          user_id INT NOT NULL,                       -- External UserManagement user ID
--                                          item_id INT NOT NULL,                       -- ID of the item/object
--                                          purchased_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--                                          description VARCHAR(255) NOT NULL,
--                                          durability_remaining INT NOT NULL,
--                                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                                          INDEX idx_inventory_user_id (user_id),
--                                          INDEX idx_inventory_item_id (item_id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- 
-- 
-- INSERT INTO inventory (user_id, item_id, purchased_at, description, durability_remaining) VALUES
--                                                                                               (1, 101, NOW(), 'Starter flashlight', 100),
--                                                                                               (1, 102, NOW(), 'EMF reader',         85),
--                                                                                               (2, 201, NOW(), 'Photo camera',        90);